#:schema node_modules/wrangler/config-schema.json
name = "portfolio"
type = "javascript"
pages_build_output_dir = ".next/standalone"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

